apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: test-clusterrolebinding
spec:
  template:
    subjects:
    - kind: Group
      name: test-user
    roleRef:
      kind: ClusterRole
      name: cluster-admin
