apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefed-controller
  namespace: {{ .Release.Namespace }}
# The comment in webhook.yaml about installing one instance also applies to the
# conditional block below.
{{ if (or (or (not .Values.global.scope) (eq .Values.global.scope "Cluster")) (not (.Capabilities.APIVersions.Has "core.kubefed.k8s.io/v1beta1"))) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: kubefed-admission-webhook
{{ end }}
